version: "3.9"

services:
  text-extractor:
    image: ghcr.io/therepos/textgrab:latest
    container_name: textgrab
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
